name: flutter_bootstrap
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0-dev <3.0.0"
  flutter: ">=1.15.2 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  collection:
  cupertino_icons:
  disposable_provider:
  enum_to_string:
  freezed_annotation:
  json_annotation:
  mono_kit: ^0.14.0-dev
  provider:
  rxdart:
  vsync_provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  pedantic_mono:
dependency_overrides:
  provider: 4.1.0-dev
flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
